import Head from 'next/head'
import React from 'react';

export const HeadPage = () => {
    return(
    <Head>
        <title>Colmena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    )
}
